NAME	= program

CC	= gcc

RM	= rm -f

SRCS	= ./create_shape.c \
	  ./entity.c \
	  ./entity_collide.c \
	  ./entity_collide_manager.c \
	  ./entity_draw.c \
	  ./my_radar.c \
	  ./arraylist/arraylist.c \

OBJS	= $(SRCS:.c=.o)

CFLAGS = -I ./include/
CFLAGS += -Wall -Wextra -g3
LDFLAGS = -lcsfml-graphics -lcsfml-window -lcsfml-system -lm

all: $(NAME)

$(NAME): $(OBJS)
	 $(CC) $(OBJS) -o $(NAME) $(LDFLAGS)

clean:
	$(RM) $(OBJS)

fclean: clean
	$(RM) $(NAME)

re: fclean all

.PHONY: all clean fclean re


re: fclean all

.PHONY: all clean fclean re


re: fclean all

.PHONY: all clean fclean re


re: fclean all

.PHONY: all clean fclean re


re: fclean all

.PHONY: all clean fclean re


re: fclean all

.PHONY: all clean fclean re


re: fclean all

.PHONY: all clean fclean re


re: fclean all

.PHONY: all clean fclean re


re: fclean all

.PHONY: all clean fclean re

re: fclean all

.PHONY: all clean fclean re

re: fclean all

.PHONY: all clean fclean re

re: fclean all

.PHONY: all clean fclean re

re: fclean all

.PHONY: all clean fclean re

re: fclean all

.PHONY: all clean fclean re

re: fclean all

.PHONY: all clean fclean re
