##
## EPITECH PROJECT, 2018
## Makefile
## File description:
## Makefile
##

SRC	=	my_popup.c\

FLAGS	=	-W -Wextra -Werror -Wall

NAME	=	my_popup

all:	$(NAME)

$(NAME):
	gcc $(FLAGS) $(SRC) -lncurses -o $(NAME)

clean:

fclean:	clean
	rm -f $(NAME)

re:	fclean all