/*
** EPITECH PROJECT, 2020
** UI_ENUMERATION_HPP
** File description:
** UI_ENUMERATION_HPP
*/

#ifndef UI_ENUMERATION_HPP
#define UI_ENUMERATION_HPP

enum
{
    GUI_ID_QUIT_BUTTON = 101,
    GUI_ID_PLAY_BUTTON = 102,
    GUI_ID_RESUME_BUTTON = 103,
    GUI_ID_LOAD_BUTTON = 104,
    GUI_ID_BACKMENU_BUTTON = 105,
    GUI_ID_SAVE_BUTTON = 106,
    GUI_ID_LAUNCH_BUTTON,
    GUI_ID_SETTINGS_BUTTON,
    GUI_ID_CREDITS_BUTTON,
    GUI_ID_MUSIC_UP_BUTTON,
    GUI_ID_MUSIC_DOWN_BUTTON,
    GUI_ID_SFX_UP_BUTTON,
    GUI_ID_SFX_DOWN_BUTTON,
};

enum
{
    GUI_ID_TITLESCREEN_INTERFACE = 201,
    GUI_ID_MAINMENU_INTERFACE,
    GUI_ID_PAUSEMENU_INTERFACE,
    GUI_ID_PLAYERSELECTION_INTERFACE,
    GUI_ID_Credits_INTERFACE,
    GUI_ID_CONTROLS_INTERFACE,
    GUI_ID_SETTINGS_INTERFACE,
    GUI_ID_END_INTERFACE
};

#endif /* !UI_ENUMERATION_HPP */
