##
## EPITECH PROJECT, 2018
## Makefile
## File description:
## Makefile
##

SRC = main.cpp useful_function.cpp fill_matrix.cpp multiply_matrix.cpp

NAME = 103cipher

all: $(NAME)

$(NAME):
	g++ $(SRC) -o $(NAME) -I./include

clean:

fclean: clean
	rm -f $(NAME)

re: fclean all