##
## EPITECH PROJECT, 2018
## Makefile
## File description:
## Makefile 101pong
##

all:
	make -C nm_dir
	make -C objdump_dir

nm:
	make -C nm_dir

objdump:
	make -C objdump_dir

clean:
	make clean -C nm_dir
	make clean -C objdump_dir

fclean: clean
	make fclean -C nm_dir
	make fclean -C objdump_dir

re:	fclean all