##
## EPITECH PROJECT, 2018
## makefile
## File description:
## makefile
##

NAME	=	evalexpr

SRC	=	*.c

all:	$(NAME)

$(NAME): 
	gcc -Wall -Wextra -Werror $(SRC) -I./include -o $(NAME)

clean:

fclean: clean
	rm -rf $(NAME)

re: fclean all