##
## EPITECH PROJECT, 2019
## makefile
## File description:
## Makefile
##

NAME = dante

all: $(NAME)

$(NAME):
	make -C ./asm

clean:
	make clean -C ./asm

fclean:
	make fclean -C ./asm

re: fclean all